// <auto-generated />
using DownloadMusic.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DownloadMusic.Migrations
{
    [DbContext(typeof(MusicDbContext))]
    [Migration("20221226051150_addproperty")]
    partial class addproperty
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DownloadMusic.Models.MusicTrackModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Album")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageFilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ImageForSave")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("MusicCategory")
                        .HasColumnType("int");

                    b.Property<string>("MusicFilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("MusicForSave")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("MusicText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Songwriter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleMusic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vocalist")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MusicTracks");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Album = "PareParvaz",
                            Description = "آهنگ فوق العاده زیبای پنجره",
                            ImageFilePath = "Null",
                            ImageForSave = new byte[] { 0, 0, 0, 0, 0 },
                            MusicCategory = 0,
                            MusicFilePath = "Null",
                            MusicForSave = new byte[] { 0, 0, 0, 0, 0, 0, 0, 0, 0 },
                            MusicText = "یه پنجره با یه قفس یه حنجره بی هم نفس",
                            Songwriter = "روزبه بمانی",
                            TitleMusic = "Panjere",
                            Vocalist = "Dariush"
                        },
                        new
                        {
                            Id = 2L,
                            Album = "PareParvaz",
                            Description = "آهنگ فوق العاده زیبای یخ زدم",
                            ImageFilePath = "Null",
                            ImageForSave = new byte[] { 0, 0, 0, 0, 0 },
                            MusicCategory = 0,
                            MusicFilePath = "Null",
                            MusicForSave = new byte[] { 0, 0, 0, 0, 0, 0, 0, 0, 0 },
                            MusicText = "گیر کردم تو شبی که  گفتی باید جداشیم",
                            Songwriter = "ایرج جنتی",
                            TitleMusic = "PareParvaz",
                            Vocalist = "Shadmehr"
                        },
                        new
                        {
                            Id = 3L,
                            Album = "PareParvaz",
                            Description = "آهنگ فوق العاده زیبای پرپرواز",
                            ImageFilePath = "Null",
                            ImageForSave = new byte[] { 0, 0, 0, 0, 0 },
                            MusicCategory = 2,
                            MusicFilePath = "Null",
                            MusicForSave = new byte[] { 0, 0, 0, 0, 0, 0, 0, 0, 0 },
                            MusicText = "تو هجوم مبهم  پنجره ها پر پرواز منو ازم نگیرید",
                            Songwriter = "منصور تهرانی",
                            TitleMusic = "Batel",
                            Vocalist = "Ebi"
                        },
                        new
                        {
                            Id = 4L,
                            Album = "HeseKhob",
                            Description = " آهنگ فوق العاده زیبای باطل",
                            ImageFilePath = "Null",
                            ImageForSave = new byte[] { 0, 0, 0, 0, 0 },
                            MusicCategory = 0,
                            MusicFilePath = "Null",
                            MusicForSave = new byte[] { 0, 0, 0, 0, 0, 0, 0, 0, 0 },
                            MusicText = "باطل است باطل نباش عزیز من",
                            Songwriter = "اردلان سرافراز",
                            TitleMusic = "YakhZadam",
                            Vocalist = "Sattar"
                        },
                        new
                        {
                            Id = 5L,
                            Album = "HeseKhob",
                            Description = "آهنگ فوق العاده زیبای حس خوب",
                            ImageFilePath = "Null",
                            ImageForSave = new byte[] { 0, 0, 0, 0, 0 },
                            MusicCategory = 1,
                            MusicFilePath = "Null",
                            MusicForSave = new byte[] { 0, 0, 0, 0, 0, 0, 0, 0, 0 },
                            MusicText = "حس خوبیه وقتی یک نفر منتظرت باشه",
                            Songwriter = "میلاد بابایی",
                            TitleMusic = "HesseKhob",
                            Vocalist = "Omid"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
